---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: CONTAINER_IMAGE
    newName: ghcr.io/lostromos-proj/lostromos
