---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lostromos-reader
subjects:
  - kind: ServiceAccount
    name: lostromos-reader
    namespace: lostromos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lostromos-reader
