---
apiVersion: v1
kind: Service
metadata:
  name: lostromos
  namespace: lostromos
  labels:
    app: lostromos
spec:
  type: ClusterIP
  selector:
    app: lostromos
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
