// Code generated by go generate; DO NOT EDIT.

package config

import (
	"flag"
)

// Config holds all runtime configuration for lostromos.
type Config struct {
	DisableConstraintInput bool
	Verbose                bool
	Kubeconfig             string
	MetricsHost            string
	MetricsPort            int
	MetricsPath            string
}

// newFlagSet returns a FlagSet with all flags bound to cfg's fields.
func newFlagSet(cfg *Config) *flag.FlagSet {
	fs := flag.NewFlagSet("lostromos", flag.ContinueOnError)
	fs.Usage = func() { printHelp() }
	fs.BoolVar(&cfg.DisableConstraintInput, "disable-constraint-input", boolEnv("DISABLE_CONSTRAINT_INPUT"), "Disable the input that watches constraint objects")
	fs.BoolVar(&cfg.Verbose, "verbose", boolEnv("VERBOSE"), "Enable verbose logging")
	fs.StringVar(&cfg.Kubeconfig, "kubeconfig", strEnv("KUBECONFIG", ""), "Path to a kubeconfig file; omit to use in-cluster config")
	fs.StringVar(&cfg.MetricsHost, "metrics-host", strEnv("METRICS_HOST", DefaultMetricsHost), "Interface to bind for the metrics HTTP endpoint")
	fs.IntVar(&cfg.MetricsPort, "metrics-port", intEnv("METRICS_PORT", DefaultMetricsPort), "Port to bind for the metrics HTTP endpoint")
	fs.StringVar(&cfg.MetricsPath, "metrics-path", strEnv("METRICS_PATH", DefaultMetricsPath), "URL path for serving metrics")
	return fs
}

// helpEntries is used by printHelp to render the usage table.
var helpEntries = []struct{ flag, env, def, desc string }{
	{"--disable-constraint-input", "DISABLE_CONSTRAINT_INPUT", "false", "Disable the input that watches constraint objects"},
	{"--verbose", "VERBOSE", "false", "Enable verbose logging"},
	{"--kubeconfig", "KUBECONFIG", "(none \u2014 in-cluster)", "Path to a kubeconfig file; omit to use in-cluster config"},
	{"--metrics-host", "METRICS_HOST", DefaultMetricsHost, "Interface to bind for the metrics HTTP endpoint"},
	{"--metrics-port", "METRICS_PORT", "9090", "Port to bind for the metrics HTTP endpoint"},
	{"--metrics-path", "METRICS_PATH", DefaultMetricsPath, "URL path for serving metrics"},
	{"--help", "", "", "Print this help message and exit"},
}
